import Center from '@/components/Center'
import Sidebar from '@/components/Sidebar'
import Head from 'next/head'
import PlaylistContextProvider from '../contexts/PlaylistContext'

export default function Home() {
   return (
      <div className="bg-black h-screen overflow-hidden">
         <PlaylistContextProvider>
            <Head>
               <title>Spotify</title>
               <meta
                  name="description"
                  content="Generated by create next app"
               />
               <meta
                  name="viewport"
                  content="width=device-width, initial-scale=1"
               />
               <link
                  rel="icon"
                  href="/favicon.ico"
               />
            </Head>
            <main className="flex">
               <Sidebar />
               <Center />
            </main>
         </PlaylistContextProvider>
      </div>
   )
}
